#!/usr/bin/env bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HELPERS_DIR="$CURRENT_DIR/helpers"

source "$HELPERS_DIR/direction_utils.sh"
source "$HELPERS_DIR/ps_utils.sh"

function get_cursor_pos() {
  local left top x y
  IFS=',' read left top x y <<< \
    $(tmux display-message -p "#{pane_left},#{pane_topupper},#{cursor_x},#{cursor_y}")
  echo "$(($left + $x)),$(($top + $y))"
}

function navigation_delay() {
  tmux show-options -gv @navigation-delay 2> /dev/null || return 0.1
}

function main() {
  local cursor dir key

  key="$1"
  dir="$2"

  cursor="$(get_cursor_pos)"
  if is_running_tmux || is_running_editor || is_running_remote; then
    tmux send-keys C-$key
    if is_running_editor || is_running_remote; then
      sleep $(navigation_delay)
    fi
  fi

  if can_select_pane $dir && [[ "$cursor" == "$(get_cursor_pos)" ]]; then
    select_pane $dir
  fi
}

main "$@"
